include:
  - ./Backend/docker-compose.yml

services:
  frontend:
    container_name: krakhouse-frontend
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "5173:80"
