spring.application.name=Backend

logging.file.name=logs/air-quality.log
logging.level.root=WARN
logging.level.pk.backend=INFO

# RestClient configuration
air-quality.api.base-url=https://api.gios.gov.pl/pjp-api